# Python Assignment: Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

## 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
# Create a list of 5 integers
L = [1,2,3,4,5]

# append

In [2]:
# append - adds one item to the end of the list
L.append(6)
L

[1, 2, 3, 4, 5, 6]

In [3]:
# extend - adds multiple items to the end of the list
L.extend([7,8,9,10])
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# insert

In [4]:
#insert - adds an item at a specific position
L.insert(2,23) # HERE 2 IS THE INDEX NUMBER AND 23 IS THE NUMBER I WANT TO ADDS ON THAT SPECIFIC INDEX NUMBER 2
L

[1, 2, 23, 3, 4, 5, 6, 7, 8, 9, 10]

# remove

In [5]:
# remove - to remove a specific value
L.remove(23)
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# pop

In [6]:
# pop - remove a last item. Also remove specific value by giving index number.
# the last number will removed from the list using this code
L.pop() 
L

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
# specific value is removed from the list by giving the index number. 
L.pop(2) 
L

[1, 2, 4, 5, 6, 7, 8, 9]

# index

In [13]:
# index - finds the position of a value
L

[1, 2, 4, 5, 6, 7, 8, 9]

In [14]:
L.index(5)

3

# count

In [15]:
# count - counts how many times a value appears
L

[1, 2, 4, 5, 6, 7, 8, 9]

In [16]:
L.count(2)

1

# sort

In [17]:
# sort - arranges the list in ascending order
L

[1, 2, 4, 5, 6, 7, 8, 9]

In [22]:
L.sort()
L

[1, 2, 4, 5, 6, 7, 8, 9]

In [23]:
# to sort in reverse manner that is in descending order we should use the code 
L.sort(reverse =True)
L

[9, 8, 7, 6, 5, 4, 2, 1]

# reverse

In [ ]:
# reverse - reverses the list

In [28]:
L

[1, 2, 4, 5, 6, 7, 8, 9]

In [29]:
L.reverse()
L

[9, 8, 7, 6, 5, 4, 2, 1]

# clear

In [30]:
# clear - removes all items
L.clear()
L

[]

# 2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [33]:
# Create a tuple containing 3 student names
T = ('Sneha','Akash','Abhijith')
T

('Sneha', 'Akash', 'Abhijith')

In [ ]:
# Try to change the second name
T[1] = 'Arun'
T

##### Explanation: A tuple is immutable, which means its elements cannot be changed after the tuple is created. Therefore, trying to change the second name results in a TypeError

## 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [40]:
# Create a set with duplicate values
S = {1,2,3,4,5,5,6,6,7,7}
# PRINT THE SET AS
S

{1, 2, 3, 4, 5, 6, 7}

##### Explanation: A set does not allow duplicate values. Therefore, when duplicate integers are added to a set, Python automatically removes the duplicates and keeps only the unique values.

## 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [50]:
# Create a dictionary
dictionary = {'name': 'Akash', 'age': 23, 'city': 'Kannur'}
dictionary

{'name': 'Akash', 'age': 23, 'city': 'Kannur'}

In [51]:
# Update the age
dictionary ['age'] = 24
dictionary

{'name': 'Akash', 'age': 24, 'city': 'Kannur'}

In [52]:
# Add a new key 'email'
dictionary ['email'] = 'akash@gmail.com'
dictionary

{'name': 'Akash', 'age': 24, 'city': 'Kannur', 'email': 'akash@gmail.com'}

## 5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [57]:
# Take age as a variable
age = 24

# Check voting eligibility

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote

##### Explanation: If the age is 18 or above, the person is eligible to vote. Otherwise, the person is not eligible to vote.

## 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [66]:
# Take marks as a variable
marks = 95

if marks>=90:
    print('Grade A')
elif marks >=75:
    print('Grade B')
elif marks >=50:
    print('Grade C')
else:
    print('Fail')

Grade A

## 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [78]:
# Check whether the number is positive, zero, or negative

n = 10
if n > 0:
    if n % 2 == 0:
        print("Positive and even")
    else:
        print("Positive and odd")
elif n == 0:
    print("Zero")
else:
    print("Negative")

Positive and even

## Section B: Numpy

### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [79]:
import numpy as np

In [97]:
# Create a scalar using np.array()
scalar = np.array(5)
scalar

array(5)

In [98]:
# Create a 1D array with values from 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [99]:
# Create a 2D array with 2 rows and 3 columns
# Values are from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],[40, 50, 60]])
array_2d

array([[10, 20, 30],
       [40, 50, 60]])

## 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [100]:
import numpy as np

array([[74, 50, 40,  2],
       [68, 37, 28, 48],
       [66,  7, 52, 92],
       [87, 30, 75, 32]], dtype=int32)

In [101]:
# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))
random_array

array([[40, 91, 82, 18],
       [ 6, 20, 51, 45],
       [59, 89, 25, 87],
       [10, 69, 34, 83]], dtype=int32)

## 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [103]:
import numpy as np
import pandas as pd

In [107]:
# Create a 3x3 NumPy array
array_2d = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

# Convert the NumPy array into a Pandas DataFrame
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])
df

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

## Section C: Exploring Pandas

### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [136]:
import pandas as pd
import numpy as np

In [137]:
# Create a small DataFrame with 10 rows
# np.nan represents a missing value in the Salary column
dic1 = {'Name': ['Akash', 'Rahul', 'Anu', 'Arun', 'Meera','Vijay', 'Anu', 'Riya', 'Kiran', 'Rahul'],
        'Age': [23, 25, 22, 28, 24, 30, 22, 26, 27, 25], 
        'City': ['Kannur', 'Kochi', 'Calicut', 'Kannur', 'Kochi','Delhi', 'Calicut', 'Mumbai', 'Bangalore', 'Kochi'],
        'Salary': [25000, 30000, 28000,np.nan ,35000,40000, 28000, 32000, 45000, 30000]}

df = pd.DataFrame(dic1)
df

    Name  Age       City   Salary
0  Akash   23     Kannur  25000.0
1  Rahul   25      Kochi  30000.0
2    Anu   22    Calicut  28000.0
3   Arun   28     Kannur      NaN
4  Meera   24      Kochi  35000.0
5  Vijay   30      Delhi  40000.0
6    Anu   22    Calicut  28000.0
7   Riya   26     Mumbai  32000.0
8  Kiran   27  Bangalore  45000.0
9  Rahul   25      Kochi  30000.0

In [138]:
# Display basic information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [139]:
# Display statistical summary of numerical columns
df.describe()

             Age        Salary
count  10.000000      9.000000
mean   25.200000  32555.555556
std     2.616189   6405.292950
min    22.000000  25000.000000
25%    23.250000  28000.000000
50%    25.000000  30000.000000
75%    26.750000  35000.000000
max    30.000000  45000.000000

In [140]:
# Select only the Name and City columns
df[['Name','City']]

    Name       City
0  Akash     Kannur
1  Rahul      Kochi
2    Anu    Calicut
3   Arun     Kannur
4  Meera      Kochi
5  Vijay      Delhi
6    Anu    Calicut
7   Riya     Mumbai
8  Kiran  Bangalore
9  Rahul      Kochi

In [141]:
# Drop the City column
df = df.drop('City', axis=1)
df

    Name  Age   Salary
0  Akash   23  25000.0
1  Rahul   25  30000.0
2    Anu   22  28000.0
3   Arun   28      NaN
4  Meera   24  35000.0
5  Vijay   30  40000.0
6    Anu   22  28000.0
7   Riya   26  32000.0
8  Kiran   27  45000.0
9  Rahul   25  30000.0

In [146]:
# Fill the missing Salary value with the mean salary
df['Salary']=df['Salary'].fillna(value= df['Salary'].mean())
df

    Name  Age        Salary
0  Akash   23  25000.000000
1  Rahul   25  30000.000000
2    Anu   22  28000.000000
3   Arun   28  32555.555556
4  Meera   24  35000.000000
5  Vijay   30  40000.000000
6    Anu   22  28000.000000
7   Riya   26  32000.000000
8  Kiran   27  45000.000000
9  Rahul   25  30000.000000

In [148]:
# Remove duplicate rows
df = df.drop_duplicates()
df

    Name  Age        Salary
0  Akash   23  25000.000000
1  Rahul   25  30000.000000
2    Anu   22  28000.000000
3   Arun   28  32555.555556
4  Meera   24  35000.000000
5  Vijay   30  40000.000000
7   Riya   26  32000.000000
8  Kiran   27  45000.000000

In [149]:
# Display the final DataFrame
df

    Name  Age        Salary
0  Akash   23  25000.000000
1  Rahul   25  30000.000000
2    Anu   22  28000.000000
3   Arun   28  32555.555556
4  Meera   24  35000.000000
5  Vijay   30  40000.000000
7   Riya   26  32000.000000
8  Kiran   27  45000.000000